def syscall_name:
  .name | ascii_upcase | gsub("[^A-Z0-9]"; "_") | gsub("_+"; "_");

"module std::os::linux::syscalls @if(env::LINUX);",
"",
"// AUTOGENERATED FILE --- DO NOT EDIT MANUALLY!",
"// Generated by `tools/gen_linux_syscalls.sh`.",
"",
"enum Syscall : (uint id, uint nparams) {",

(.syscalls[] | "\t\(syscall_name) { \(.number), \(.signature | length) }, // (\(.signature | join(", ")))"),

"}"
