name: clang-format Check

on: [push, pull_request]

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: "Formatting Check"
    runs-on: ubuntu-latest
    strategy:
          matrix:
            path:
              - 'src'
              - 'tb'
              - 'wrapper'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ sources.
      uses: jidicula/clang-format-action@v4.6.2
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
        fallback-style: 'Microsoft'
